/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package usuario;

import javax.swing.JOptionPane;

/**
 *
 * @author Nacho
 */
public class AdministrarNuevoJugador extends javax.swing.JFrame {

    /**
     * Creates new form AdmNueJuga
     */
    public AdministrarNuevoJugador() {
        initComponents();
        labelNuevoJugador.setText(Menu.nuevoMiembro.getNombre()+" "+Menu.nuevoMiembro.getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNuevoJugador = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bAceptado = new javax.swing.JButton();
        bRechazado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Administrar Nuvo Jugador");

        jLabel2.setText("Este nuevo jugador quiere inscribirse:");

        labelNuevoJugador.setText("mostrarJugador");

        jLabel4.setText("Lo aprueba?");

        bAceptado.setText("Si");
        bAceptado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptadoActionPerformed(evt);
            }
        });

        bRechazado.setText("No");
        bRechazado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRechazadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNuevoJugador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(bAceptado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bRechazado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNuevoJugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptado)
                    .addComponent(bRechazado))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptadoActionPerformed
        Menu.miembros.add(Menu.nuevoMiembro);
        JOptionPane.showMessageDialog(this, "El nuevo jugador se ha agregado correctamente", "Información",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        Menu.nuevoMiembro= null;
    }//GEN-LAST:event_bAceptadoActionPerformed

    private void bRechazadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRechazadoActionPerformed
        Menu.nuevoMiembro= null;
        (new NotificarJugador()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bRechazadoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptado;
    private javax.swing.JButton bRechazado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelNuevoJugador;
    // End of variables declaration//GEN-END:variables
}
