/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package futbol5app;

/**
 *
 * @author Familia
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonOrgPartido = new javax.swing.JButton();
        botonInscribPartido = new javax.swing.JButton();
        botonDarseBaja = new javax.swing.JButton();
        botonNuevoJugador = new javax.swing.JButton();
        botonAdminNuevoJugador = new javax.swing.JButton();
        botonGenerarEq = new javax.swing.JButton();
        botonCalificar = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonOrgPartido.setText("Organizar Partido");
        botonOrgPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonOrgPartidoMouseClicked(evt);
            }
        });
        botonOrgPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrgPartidoActionPerformed(evt);
            }
        });

        botonInscribPartido.setText("Inscribirse al partido");
        botonInscribPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInscribPartidoMouseClicked(evt);
            }
        });

        botonDarseBaja.setText("Darse de baja del partido");
        botonDarseBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDarseBajaMouseClicked(evt);
            }
        });

        botonNuevoJugador.setText("Incorporar nuevo jugador");
        botonNuevoJugador.setMaximumSize(new java.awt.Dimension(159, 23));
        botonNuevoJugador.setMinimumSize(new java.awt.Dimension(159, 23));
        botonNuevoJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNuevoJugadorMouseClicked(evt);
            }
        });

        botonAdminNuevoJugador.setText("Administrar nuevo jugador");
        botonAdminNuevoJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAdminNuevoJugadorMouseClicked(evt);
            }
        });

        botonGenerarEq.setText("Generar equipos tentativos");
        botonGenerarEq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGenerarEqMouseClicked(evt);
            }
        });

        botonCalificar.setText("Calificar jugadores");
        botonCalificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCalificarMouseClicked(evt);
            }
        });

        botonCerrar.setText("Cerrar programa");
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenido al Sistema de Partidos");

        jLabel2.setText("Seleccione una opción: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCerrar)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botonCalificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGenerarEq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(botonNuevoJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonInscribPartido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonOrgPartido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonDarseBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAdminNuevoJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonOrgPartido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonInscribPartido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonDarseBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNuevoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAdminNuevoJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGenerarEq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCalificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botonCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOrgPartidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOrgPartidoMouseClicked
        new OrganizarPartido().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonOrgPartidoMouseClicked

    private void botonInscribPartidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInscribPartidoMouseClicked
        new InscribirJugador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonInscribPartidoMouseClicked

    private void botonDarseBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDarseBajaMouseClicked
        new DarseBaja().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonDarseBajaMouseClicked

    private void botonNuevoJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoJugadorMouseClicked
        new IncorporarNuevoJugador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonNuevoJugadorMouseClicked

    private void botonAdminNuevoJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAdminNuevoJugadorMouseClicked
        new AdministrarNuevoJugador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonAdminNuevoJugadorMouseClicked

    private void botonGenerarEqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGenerarEqMouseClicked
        new GenerarEquiposTentativos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGenerarEqMouseClicked

    private void botonCalificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCalificarMouseClicked
        new CalificarJugadores().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCalificarMouseClicked

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        fin = true;
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void botonOrgPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrgPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonOrgPartidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdminNuevoJugador;
    private javax.swing.JButton botonCalificar;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonDarseBaja;
    private javax.swing.JButton botonGenerarEq;
    private javax.swing.JButton botonInscribPartido;
    private javax.swing.JButton botonNuevoJugador;
    private javax.swing.JButton botonOrgPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
